apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: docker.getcollate.io/openmetadata/ingestion:1.5.0
          ports:
            - containerPort: 8080