apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata
  template:
    metadata:
      labels:
        app: openmetadata
    spec:
      containers:
        - name: openmetadata
          image: docker.getcollate.io/openmetadata/server:1.5.0
          ports:
            - containerPort: 8585