apiVersion: v1
kind: Service
metadata:
  name: openmetadata-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8585
    - port: 80
      targetPort: 8586
  selector:
    app: openmetadata