apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: nginx-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

# Apply the resources:
# kubectl apply -f /vagrant/teste-eks-amazon/pvc.yaml

# Check the resources:
# kubectl get pods
# kubectl get pvc

# Destroy the resources:
# kubectl delete -f /vagrant/teste-eks-amazon/pvc.yaml